
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-deliverysystem8282-com-tls
  namespace: argocd
spec:
  secretName: argo-deliverysystem8282-com-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: argo.deliverysystem8282.store
  dnsNames:
  - argo.deliverysystem8282.store